FROM openemr/openemr:8.3.0

COPY interface/themes/oe-styles/style_light.scss /var/www/localhost/htdocs/openemr/interface/themes/oe-styles/style_light.scss
COPY custom/branding/preview.html /var/www/localhost/htdocs/openemr/custom/branding/preview.html
COPY custom/branding/sw.js /var/www/localhost/htdocs/openemr/custom/branding/sw.js
COPY sites/default/images/logos/ /var/www/localhost/htdocs/openemr/sites/default/images/logos/
